
import { GoogleGenAI } from '@google/genai';
import { AspectRatio } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateThumbnail(prompt: string, aspectRatio: AspectRatio): Promise<string[]> {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 4,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      return response.generatedImages.map(image => {
        const base64ImageBytes: string = image.image.imageBytes;
        return `data:image/jpeg;base64,${base64ImageBytes}`;
      });
    } else {
      throw new Error("No images were generated by the API.");
    }
  } catch (error) {
    console.error("Error generating images with Gemini API:", error);
    throw error;
  }
}

export async function enhancePrompt(concept: string, language: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `You are an expert YouTube thumbnail designer and prompt engineer for high-end AI image generators like Imagen.
      
      User's Rough Concept: "${concept}"
      Target Language for Text in Image: "${language}"

      Your task is to write a single, highly detailed image generation prompt.
      
      Guidelines:
      1. Describe the main subject with vivid detail (expression, pose, clothing).
      2. Describe the background, lighting, and color palette (e.g., "vibrant neon", "cinematic lighting", "high contrast").
      3. If the language is not "No Text", suggest a short, catchy 2-3 word phrase in the specified language to appear on the thumbnail. Describe the font style (e.g., "big bold yellow text").
      4. If the language is "No Text", strictly avoid describing any text.
      5. The output must be the raw prompt string only, suitable for pasting directly into an image generator. Do not include quotes or conversational filler.
      6. Ensure the artistic style is "photorealistic", "4k", or "hyper-realistic" unless the concept suggests otherwise.
      `,
    });

    return response.text || concept;
  } catch (error) {
    console.error("Error enhancing prompt:", error);
    throw error;
  }
}
